### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#10]
![image](https://cloud.githubusercontent.com/assets/15248543/18952054/dc958c58-860d-11e6-90a1-229f0bfd9af7.png)

**Comment by kevinheath** [comment]
This is not working for either

**Comment by kevinheath** [comment]
The image file upload is still not working. It lets you place any type of file but does not work. Additionally, when I load a correct image you do not see anything and if forces you to save before, however once saved it moves you to work info. This should not be like this. Please fix.

**Comment by baansconsulting** [comment]
will be done by tomorrow

**Comment by baansconsulting** [comment]
if you upload the image it will show you the change image. but user has to still click Save button to save it back to database
