### ISSUE TITLE
excel upload download

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#11]
![upload](https://cloud.githubusercontent.com/assets/15248543/18952084/02c10538-860e-11e6-87d2-8fca911d1f06.png)

**Comment by baansconsulting** [comment]
Can you please share the excel template, which will help us to design the upload for client contacts to database?

**Comment by kevinheath** [comment]
would this not be a simple spreadsheet that includes all possible fields for contacts. If we exported contacts to a spreadsheet, this would be that template

**Comment by kevinheath** [comment]
Not completed

**Comment by kevinheath** [comment]
update
