### ISSUE TITLE
Docs Tab

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#12]
![12](https://cloud.githubusercontent.com/assets/15248543/18952169/565456c8-860e-11e6-991e-54cd01bc1e1d.png)

**Comment by baansconsulting** [comment]
fixed

**Comment by kevinheath** [comment]
This should be center cell like Quote. Now they are all on Top

**Comment by kevinheath** [comment]
Not Complete - Milestone Added

**Comment by baansconsulting** [comment]
Bhavna's suggestion to align all text in top (text top left align) and numeric (all values right aligned)
