### ISSUE TITLE
Database COI

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#124]
![2](https://cloud.githubusercontent.com/assets/15248543/20836097/645061e0-b863-11e6-99ec-d86ba1594ecd.png)

**Comment by baansconsulting** [comment]
I think we discussed that you would like to see the status on the top in COI

We are also working to replace "Add insurance document" as dynamic creation of button so that it become easy for you to create the document (just change values) rather for each client you have create the PDF separately.
