### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#18]
![1](https://cloud.githubusercontent.com/assets/15248543/18952455/477a4738-860f-11e6-802a-cd2b2a707bb5.png)

**Comment by baansconsulting** [comment]
Account Manager issue is fixed.
Subagent issue fixed
Nature of business is working...I think it was working on your old 26 inc monitor machine.
we are working to fixed rest

**Comment by kevinheath** [comment]
nature of business still locking up

**Comment by baansconsulting** [comment]
Its working fine at our end. I tried this from my home, office and other desktop outside, its working. We made some code changes. can you try again on your new machine and other machines/laptop as well?
