### ISSUE TITLE
deleting drop downs

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#23]
![1](https://cloud.githubusercontent.com/assets/15248543/19057632/e7ef2a78-8996-11e6-97d2-600a529566e1.png)

Please remove these dropdowns.

**Comment by baansconsulting** [comment]
done

**Comment by kevinheath** [comment]
Please add Public Officials only. This will give us EPLI, Public Officials & EPLI/Public Officials as options

**Comment by kevinheath** [comment]
Still need to add Public Officials stand alone

**Comment by baansconsulting** [comment]
added Public Officials
