### ISSUE TITLE
change

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#27]
![6](https://cloud.githubusercontent.com/assets/15248543/19058177/d5b907a8-899a-11e6-8c84-58531a64113f.png)

**Comment by baansconsulting** [comment]
we have added website as link, so when user click on it will take to website

**Comment by kevinheath** [comment]
What about address: sending you to google maps

**Comment by kevinheath** [comment]
Address or map not taking us to google maps
