### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#28]
![5](https://cloud.githubusercontent.com/assets/15248543/19058205/05b527de-899b-11e6-99e9-bab754667cf8.png)

**Comment by baansconsulting** [comment]
done

**Comment by kevinheath** [comment]
![1](https://cloud.githubusercontent.com/assets/15248543/19116865/8eaf9096-8adc-11e6-877a-9c7afb4ffd3f.png)
See attached

**Comment by baansconsulting** [comment]
done

**Comment by kevinheath** [comment]
Okay - I think I confused this one. I do not think we need contact "Status" field at all. Also do not need contact database button, as the user Role will determine if they have database access. 
![1](https://cloud.githubusercontent.com/assets/15248543/19187743/f6307f42-8c52-11e6-900d-d3c194629d6b.png)

**Comment by baansconsulting** [comment]
done
