### ISSUE TITLE
Contact setup

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#30]
![contact setup](https://cloud.githubusercontent.com/assets/15248543/19070788/9bda8ec8-89f2-11e6-991e-f659b5b54b8f.png)

After loading personal info, should we save and then open work information if needed?

**Comment by baansconsulting** [comment]
there was 1 point raised saying once user click save, it will take it back to contact list/table. So do we need the change shared above?

**Comment by kevinheath** [comment]
Not sure I understand. The idea would be that we can load personal information then have the option to open work info or save. Once saved it takes us back to client

**Comment by baansconsulting** [comment]
done
