### ISSUE TITLE
Single Click

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#36]
As discussed, when we place mouse on an item such as a client we should only have to single click

**Comment by baansconsulting** [comment]
we have implemented where we show client list. Once you confirm, we will implement in other areas. Please confirm?

**Comment by kevinheath** [comment]
This is not working for other tables (quotes, claims, policies, etc.)

**Comment by baansconsulting** [comment]
once your confirm its working for client list, we will implement in other areas tomorrow.

**Comment by baansconsulting** [comment]
90% done. As its in complete web application in lot of areas. Will be complete by this week friday

**Comment by baansconsulting** [comment]
implemented across all areas. Let us know if any more areas it needs to be implemented
