### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#39]
![1](https://cloud.githubusercontent.com/assets/15248543/19075558/10042b16-8a0b-11e6-8eff-aeff1b2fedcc.png)

**Comment by baansconsulting** [comment]
fixed

**Comment by kevinheath** [comment]
Not getting error on email address as duplicate. Also should this also apply for the entire client contacts.

**Comment by baansconsulting** [comment]
email address as duplicate will be checked when user click SAVE button
