### ISSUE TITLE
year co established

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#43]
![1](https://cloud.githubusercontent.com/assets/15248543/19186641/d9259460-8c4c-11e6-96fe-d3941c6adc69.png)

**Comment by baansconsulting** [comment]
![company year](https://cloud.githubusercontent.com/assets/8331184/19211039/e0dae200-8d50-11e6-882b-36106c8a4b25.png)

**Comment by baansconsulting** [comment]
This is how it appears at my end.  I tried one of my remote desktop machine in US and it shows the same. Is this problem on other computers. Looks like there are some different settings on your machine, which we have to understand so that we can fix nature of business and company year issue
