### ISSUE TITLE
Delete Client

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#46]
Also remove delete option a client table level

![2](https://cloud.githubusercontent.com/assets/15248543/19187891/c829689c-8c53-11e6-968f-7ca6e1c7dc07.png)

**Comment by kevinheath** [comment]
![1](https://cloud.githubusercontent.com/assets/15248543/19188994/2772b108-8c5b-11e6-9b06-9b87667623d2.png)

**Comment by baansconsulting** [comment]
We have removed "Delete Client" button and have changed different functionality. Only Administrator user can see "Delete" option just like we have "Insured", "Prospects", "Inactive" option. Once you select "Delete" option, it will popup the message. You check or we can discuss, show you demo and take your inputs

**Comment by baansconsulting** [comment]
Further, administrator and change the status from Delete to Insured or Prospects and it will again become active. we can discuss

**Comment by baansconsulting** [comment]
we will give you demo in detail and how we Administrator can recover the client. can discuss and take your inputs

**Comment by kevinheath** [comment]
Not seeing the delete client option any longer. Are you testing?

**Comment by baansconsulting** [comment]
we will give you demo of this, how delete client will work
