### ISSUE TITLE
Sort Filters for tables

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#53]
![1](https://cloud.githubusercontent.com/assets/15248543/19188700/1763cc18-8c59-11e6-9222-81f108fc8023.png)

**Comment by kevinheath** [comment]
No sort for this or other tables

**Comment by kevinheath** [comment]
Not fixed

**Comment by baansconsulting** [comment]
if you click the column heading of table, it will sort the table. Happy discuss if its not working at your end.

**Comment by kevinheath** [comment]
![1](https://cloud.githubusercontent.com/assets/15248543/19474759/9c105788-94f6-11e6-9862-5d9f8eeb7adc.png)

**Comment by baansconsulting** [comment]
its applied in Client list and edit client areas. rest will be applied by tomorrow

**Comment by baansconsulting** [comment]
pending only in Setup tables which we will complete by tomorrow, saturday
