### ISSUE TITLE
Class Codes

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#54]
![1](https://cloud.githubusercontent.com/assets/15248543/19188782/b1beee82-8c59-11e6-84db-e3967bf68a23.png)

**Comment by kevinheath** [comment]
Part of this is done and thanks.  Still need sort as part of this and **all tables.** Also need the import and export table as discussed above

**Comment by baansconsulting** [comment]
Class code list will apply for all clients? It will not be different for Clients
