### ISSUE TITLE
save buttons

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#58]
![1](https://cloud.githubusercontent.com/assets/15248543/19435885/c4b58bc8-9432-11e6-9e89-3e9db47cc66b.png)

**Comment by kevinheath** [comment]
milestone added

**Comment by baansconsulting** [comment]
done

**Comment by kevinheath** [comment]
Do not see this button change

**Comment by baansconsulting** [comment]
we will have "Save" button only but when you click on it, you will see it will collapse 1 area and open other

**Comment by baansconsulting** [comment]
need to review together
