### ISSUE TITLE
About Tab and more

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#60]
![1](https://cloud.githubusercontent.com/assets/15248543/19436619/d67fd238-9436-11e6-8d29-549ae0a2683c.png)

**Comment by kevinheath** [comment]
milestone added

**Comment by baansconsulting** [comment]
We have moved About tab as collapsible area in Client Tab Instead of checkbox we have further added collapsible areas in About area. Please advice
