### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#62]
![1](https://cloud.githubusercontent.com/assets/15248543/19473777/92765e2e-94f2-11e6-9e22-69f8f233eb1a.png)

**Comment by kevinheath** [comment]
There is also a flicker of the map when opening up any part of the database. Hopefully, this will fix it

**Comment by baansconsulting** [comment]
we have removed flickering. you can check on CONTACT tab in edit client. we will remove flickering in other areas by tomorrow
