### ISSUE TITLE
Delete Client

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#63]
![1](https://cloud.githubusercontent.com/assets/15248543/19569647/21d5da5c-96bc-11e6-9330-cbc3342576c1.png)

**Comment by baansconsulting** [comment]
if you select "Delete" option, in client table you will find status delete. Only administrator can change from delete to insured or .....etc..

**Comment by baansconsulting** [comment]
based on our discussion, we will finish by Saturday
