### ISSUE TITLE
Inception Date

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#72]
![1](https://cloud.githubusercontent.com/assets/15248543/19930315/ecd5d6f8-a0d5-11e6-90ed-546f23c321a2.png)

**Comment by baansconsulting** [comment]
we discussed this point earlier and you have shared let it be flexible for user. but now as suggested we will default to 1 year and user can modify

**Comment by baansconsulting** [comment]
i think its working, I press button "Add new Quote" and see the Inception Date is set for 1 year say today's date is 11/03 then inception date set as "11/03/2016 - 11/02/2017". User can still modify the date.

**Comment by kevinheath** [comment]
Not Working
![1](https://cloud.githubusercontent.com/assets/15248543/20100986/80a26582-a585-11e6-867c-0f8f6650f17e.png)

**Comment by baansconsulting** [comment]
It works, you have to first select FROM Date and then select TO date

**Comment by kevinheath** [comment]
No if you choose the inception date the expiration date should default to one year however you can change the x date. That is not what is happing

Kevin Heath
Vice President
Acentria, Inc.
1007 Jenks Ave.
Panama City, Fl. 32405
W: 850-257-2980
C: 850-866-3283
F: 850-257-2991
[acentria logo b&w]
Acentria is an independent agency striving to contribute to our clients’ security and success by providing insurance and risk management services.”

PLEASE NOTE: ALL COVERAGE AMENDMENTS/ADDITIONS/DELETIONS ARE SUBJECT TO INSURANCE COMPANY APPROVAL
This email and any attachments are intended only for use by the addressee(s) named and may contain legally privileged or confidential information, or both. If you are not the intended recipient of this email, you are notified that any dissemination, distribution or copying of this email, and any attachments, is prohibited. The unauthorized disclosure or interception of email is a federal crime. See 18 U.S.C. Section 2511. If you have received this email in error, please immediately notify me at (850-650-1950) or at mail@acentria.commailto:mail@acentria.com and permanently delete the original and any copy of any e-mail and any printout.

**Comment by baansconsulting** [comment]
When I say...Add Quote, it set the 1 yr inception date. if you open any existing quote it allows to change from and to date...you have to also click "Apply" button.

I can show you demo. we have meeting tomorrow.
