### ISSUE TITLE
saving

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#79]
![1](https://cloud.githubusercontent.com/assets/15248543/20265334/202bc2b0-aa36-11e6-8e22-5fc2c23fd0b2.png)

**Comment by baansconsulting** [comment]
can you share steps when you get this error? also please share claim id

**Comment by kevinheath** [comment]
I am simply hitting the save button after loading information in above bars

**Comment by baansconsulting** [comment]
not able to reproduce the issue. can you please try again and share screen with us
